apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.33.0"
appVersion: "1.0.4-1-NOD-463-fix-prod"
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
