apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.49.0"
appVersion: "1.2.5-2-NOD-724-api-assistenza-status-snapshot"
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
