apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.16.0"
appVersion: "1.0.2-11-NOD-400"
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
