apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.58.0"
appVersion: "1.2.8-NOD-857-fix-prod"
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
