microservice-chart:
  namespace: "nodo"
  image:
    repository: ghcr.io/pagopa/pagopa-node-technical-support-worker
    tag: '1.2.3'
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 8
    failureThreshold: 10
    periodSeconds: 2
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 8
    failureThreshold: 10
    periodSeconds: 2
  envConfig:
    APP_ENVIRONMENT: "dev"
    TZ: "Europe/Rome"
    OTEL_ENDPOINT: "http://otel-collector.elastic-system.svc.cluster.local:4317"
    COSMOS_BIZ_ENDPOINT: "https://pagopa-d-weu-bizevents-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_NEG_BIZ_ENDPOINT: "https://pagopa-d-weu-bizevents-neg-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_VERIFYKO_ENDPOINT: "https://pagopa-d-weu-nodo-verifyko-cosmos-account.documents.azure.com:443/"
    DATASOURCE_USERNAME: "pp_nodo4_cfg"
    DATASOURCE_URL: "jdbc:postgresql://db-postgres-ndp.d.db-nodo-pagamenti.com:5444/ndpspct?prepareThreshold=0&currentSchema=NODO4_CFG"
    DB_SERVICE_IDENTIFIER: "NDP004DEV"
    LOG_LEVEL: "INFO"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  secretProvider:
    create: true
    envSecrets:
      OTEL_AUTH_BEARER: "otel-auth-bearer"
      COSMOS_BIZ_KEY: "cosmos-biz-account-key"
      COSMOS_NEG_BIZ_KEY: "cosmos-neg-biz-account-key"
      COSMOS_VERIFYKO_KEY: "cosmos-verifyko-account-key"
      DATASOURCE_PASSWORD: "db-nexi-cfg-password"
    keyvault:
      name: "pagopa-d-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "400M"
      cpu: "200m"
    limits:
      memory: "3Gi"
      cpu: "400m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "75"
      - type: memory
        metadata:
          type: Utilization
          value: "75"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  serviceMonitor:
    create: true
    endpoints:
      - interval: 5s
        targetPort: 8080
        path: /q/metrics
  service:
    create: true
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /pagopa-nodo-technical-support-service(/|$)(.*)
  canaryDelivery:
    deployment:
      image:
        tag: 1.0.3-5-using_re_cosmos_nosql
    create: false
